### ISSUE TITLE
Make it more clear what the demo button does. Draw more attention to it

### ISSUE THREAD

**Issue by Cameronwyatt** [kyetter/ansible-devspace-demo#20]
Status badge are typically used to show status and then provide more information when clicked on. I found it a bit confusing that the button at the top of the readme is how you actually launch the demo. Consider switching to another mechanism for launching the demo such as a different button, or at least call more attention to the one that exists currently

**Comment by HunterGerlach** [comment]
I think what @kyetter has done is [a great emerging paradigm for status badges](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.4/html-single/user_guide/index#first-time-contributors). While it's been around for [a few years](https://github.com/redhat-developer/rh-che/blame/0d6fe4d58cfa56f093e6f52628c0c636081bfae0/README.md#L6), it hasn't quite caught on yet.


I do agree that there should be more attention called to the badge's purpose since it's likely new to a lot of people and it's therefore overloading their expectations for badges. Something as simple as adding `To get started, simply click the button below...` before the badge may be enough.

**Comment by HunterGerlach** [comment]
https://github.com/kyetter/ansible-devspace-demo/pull/21
